### ISSUE TITLE
register : send JWT by email instead of responding with Json User

### ISSUE THREAD

**Issue by juliensie** [fairhive-labs/preregister#1]
We must validate user's email for future airdrops.

There will be a lot of scams, I feel uncomfortable recording useless entries in the system... stateless approach looks better anyway.

When a user provides its c-chain (ETH) address + email + type (client/agent/mentor/talent), the system send an email with an activation link using a JWT token including these data.

The token should expire in 1 hour.

We should store data only when tokens are well validated, preventing to store useless data with a simple flag that must be updated after activation.

**Comment by IndieNation** [comment]
Can you please add an "investors" type.

**Comment by juliensie** [comment]
will do 💚
